spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.122.10:3306/mt_cloud_middle?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
  mail:
    host: smtp.163.com
    username: 18589998412@163.com
    password: BVMNYDZNBLRIOCOI
    properties.mail.display.sendmail: 验证码
    properties.mail.display.sendname: Motb Account Register
  zipkin:
    base-url: http://192.168.122.10:9411
    enabled: true
  sleuth:
    web:
      enabled: true
    feign:
      enabled: true
    log:
      slf4j:
        enabled: true

# mybatis配置
mybatis:
  mapper-locations: classpath:mybatis/*.xml
  configuration:
    map-underscore-to-camel-case: true

#文件服务配置
minio:
  enable: true
  endpoint: http://192.168.122.10:9000
  accessKey: useraccess
  secretKey: mysecret

#系统自定义配置
system:
  enable-token-auth: true

logging:
  level:
    root: info
    com.mt.middle.dao: debug
  file:
    max-size: 20MB
    path: ${spring.application.name}-log

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    prefer-ip-address: true

#分布式事务配置
seata:
  tx-service-group: book_group #事务组
  service:
    vgroup-mapping:
      book_group: seata-server #服务名
    grouplist:
      seata-server: 192.168.120.128:18090
  enabled: false

### 调度中心部署跟地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
xxl:
  enable: true
  ip: #执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
  port: 9999 #执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；
  app-name: ${spring.application.name} # 执行器 AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
  access-token: # 执行器通讯TOKEN [选填]：非空时启用
  log-path: /data/applogs/xxl-job/jobhandler # 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
  log-retention-days: 30 # 执行器日志文件保存天数 [选填] ： 过期日志自动清理, 限制值大于等于3时生效; 否则, 如-1, 关闭自动清理功能；
  admin-addresses: http://192.168.122.10:8888/xxl-job-admin # 调度中心部署跟地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
